### DISCUSSION TITLE
Welcome to hass-opensprinkler Discussions!

### DISCUSSION THREAD

**Discussion by vinteo** [vinteo/hass-opensprinkler#143] [General]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by LotharKnysna** [comment]
Hi, 
I am still a rookie with home assistant and try to controll my two opensprinklers with HA. Unfortunately while installing the integration, there were no questions about url or password. Can you advise in which config file I must write the info? And can I add this twice to connect both opensprinklers?
Thanks for helping!
Lothar from South Africa

**Reply by vinteo** [reply]
After you installed the integration through HACS, in HA -> Configuration -> Integrations at the bottom right there is an `Add Integration` button at the bottom right. Click on it to add integrations.

![image](https://user-images.githubusercontent.com/819711/104243516-c7ed5b80-54b4-11eb-9006-9955f7f52b94.png)

Search for `OpenSprinkler` in the modal that pops up and click on it:

![image](https://user-images.githubusercontent.com/819711/104243627-f53a0980-54b4-11eb-8eeb-e0075c66f39a.png)

Then the configuration modal should pop up (the first time you do this it may take a while as it is installing dependencies):

![image](https://user-images.githubusercontent.com/819711/104243689-10a51480-54b5-11eb-8a41-ef2c7b97ffce.png)

Fill it out and submit. 

Repeat from beginning each time for each of your OpenSprinkler devices.

**Comment by LotharKnysna** [comment]
Thank you very much ! I just didn’t realize that I had to add in in configurations again. 
Runs perfect!

Am 12.01.2021 um 00:07 schrieb Vincent Teo <notifications@github.com>:

﻿
After you installed the integration through HACS, in HA -> Configuration -> Integrations at the bottom right there is an Add Integration button at the bottom right. Click on it to add integrations.



Search for OpenSprinkler in the modal that pops up and click on it:



Then the configuration modal should pop up (the first time you do this it may take a while as it is installing dependencies):



Fill it out and submit.

Repeat from beginning each time for each of your OpenSprinkler devices.

**Comment by neketu** [comment]
I've been digging through forums and outside searches and cannot find the answer to what seems to be a simple use case for my integration. I'd like to have a scene/automation trigger when my system is watering, and again when watering is complete. The reason is that I have a Flo water leak detection that always misreads the irrigation and shuts off my water (usually in the middle of the night!). Now that Flo has an integration in HASS that allows you to set it to 'away' mode, I can setup an automation that puts Flo to sleep while my sprinklers are running and back to 'guard' mode when they are not running to eliminate false alarms due to my irrigation. Is there such a flag or parameter I can key from? I'm really hoping the answer doesn't involve having to poll or monitor every zone. TIA!

**Reply by vinteo** [reply]
I have automation for each station that uses the `status` entity as a trigger. For example the following triggers for all scenarios when the station starts running:

```
trigger:
    - entity_id: sensor.fruits_station_status, sensor.flowers_station_status, sensor.herbs_station_status, sensor.vegetables_station_status
      platform: state
      to: manual
    - entity_id: sensor.fruits_station_status, sensor.flowers_station_status, sensor.herbs_station_status, sensor.vegetables_station_status
      platform: state
      to: once_program
    - entity_id: sensor.fruits_station_status, sensor.flowers_station_status, sensor.herbs_station_status, sensor.vegetables_station_status
      platform: state
      to: program
```

And this for it when it stops:

```
trigger:
    - entity_id: sensor.fruits_station_status, sensor.flowers_station_status, sensor.herbs_station_status, sensor.vegetables_station_status
      platform: state
      to: idle
```
