### ISSUE TITLE
v1.0.3 - No station switches available to pass to opensprinkler.run

### ISSUE THREAD

**Issue by ryanm7780** [vinteo/hass-opensprinkler#100]
After upgrading past v1.0, I don't have any station or program switches.  It creates:
`
switch.StationName_enabled
binary_sensor.StationName_running
switch.ProgramName_enabled
binary_sensor.ProgramName_running
`
but nothing that it looks like I could pass as an entity_id to opensprinkler.run.  I could well just be misinterpreting something with this new design, but I don't see what I'm meant to pass to the run service.  Neither the switches nor the programs have anything like switch.StationName or switch.ProgramName, which is what the documentation calls for to be passed as an entity_id to the run service.

**Comment by travisghansen** [comment]
@ryanm7780 for that time being it's by design that's correct. Invoke `opensprinker.run` on any of the program/station entities and it should work.

**Comment by travisghansen** [comment]
Here's an example to use with auto-entities that mimics the old behavior in the UI:

```
card:
  show_header_toggle: false
  title: OpenSprinkler Station Status
  type: entities
filter:
  include:
    - entity_id: sensor.*_station_status*
      options:
        tap_action:
          action: call-service
          service: opensprinkler.run
          service_data:
            entity_id: this.entity_id
type: 'custom:auto-entities'
```

- https://github.com/thomasloven/lovelace-auto-entities
