### ISSUE TITLE
Run Once Program turns off all the other programs

### ISSUE THREAD

**Issue by JurajNyiri** [vinteo/hass-opensprinkler#104]
When using a new run once program feature, to turn on multiple stations at the same time, it turns off all the others.

Replication steps:
1. Turn on s08
2. Run this:
```
- service: opensprinkler.run
   data:
        entity_id: switch.opensprinkler_enabled
        run_seconds:
          - index: 0
            run_seconds: 64800
          - index: 2
            run_seconds: 64800
          - index: 5
            run_seconds: 64800
```
3. s08 is now turned off

Now this might be an intended behaviour but it surprised me. I have many automations turning on/off stations independently from each-other and since implementing the run-once-programs new feature, it has been turning all the others off.

Description should be updated with a **bold** warning or if possible, this behaviour should be changed.

For now I am going back to sequential turn/on/off of individual stations.
