### ISSUE TITLE
Example in README.md is broken

### ISSUE THREAD

**Issue by maorcc** [vinteo/hass-opensprinkler#126]
The following example seems broken:

```yaml
switch:
  - platform: template
    switches:
      fruits_station:
        value_template: "{{ is_state('binary_sensor.s01_station_running', 'on') }}"
        turn_on:
          service: opensprinkler.run
          data_template:
            entity_id: binary_sensor.s01_station_running
            # Run seconds uses the input_number below.
            run_seconds: "{{ ((states('input_number.s01_station_minutes') | float) * 60) | int }}"
        turn_off:
          service: opensprinkler.stop
          data:
            entity_id: binary_sensor.s01_station_running
​
input_number:
  s01_station_minutes:
    initial: 1
    min: 1
    max: 10
    step: 1
```

Causing an error in the log that ```binary_sensor.s01_station_running``` not found.
