### ISSUE TITLE
Unable to find referenced entities switch.opensprinkler_enabled

### ISSUE THREAD

**Issue by garithd** [vinteo/hass-opensprinkler#144]
Running Home Assistant version 2020.12.2 and using this config at the bottom of this msg.

When using lovelace to manually run a single station, using the slider inputs, the station is turned on and works as expected. In contrast, when using the 'water_garden' switch I created, to run a few stations one after the next, nothing happens.

Looking at the logs I found this:

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:102
First occurred: 20:44:24 (1 occurrences)
Last logged: 20:44:24

Unable to find referenced entities switch.opensprinkler_enabled
```
After some searching, looks like a change in HA since 0.106.x that could have broken things, though I'm not entirely sure: https://github.com/home-assistant/core/issues/36128

My current guess is that I need to call the controller differently and not use 'switch.opensprinkler_enabled', any ideas?

```
switch:
  - platform: template
    switches:
      front_beds:
        value_template: "{{ is_state('binary_sensor.frontbeds_station_running', 'on') }}"
        turn_on:
          service: opensprinkler.run
          data_template:
            entity_id: binary_sensor.frontbeds_station_running
            # Run seconds uses the input_number below.
            run_seconds: "{{ ((states('input_number.frontbeds_timer') | float) * 60) | int }}"
        turn_off:
          service: opensprinkler.stop
          data:
            entity_id: binary_sensor.frontbeds_station_running
      front_grass:
        value_template: "{{ is_state('binary_sensor.frontgrass_station_running', 'on') }}"
        turn_on:
          service: opensprinkler.run
          data_template:
            entity_id: binary_sensor.frontgrass_station_running
            # Run seconds uses the input_number below.
            run_seconds: "{{ ((states('input_number.frontgrass_timer') | float) * 60) | int }}"
        turn_off:
          service: opensprinkler.stop
          data:
            entity_id: binary_sensor.frontgrass_station_running
      pool_garden:
        value_template: "{{ is_state('binary_sensor.poolgarden_station_running', 'on') }}"
        turn_on:
          service: opensprinkler.run
          data_template:
            entity_id: binary_sensor.poolgarden_station_running
            # Run seconds uses the input_number below.
            run_seconds: "{{ ((states('input_number.poolgarden_timer') | float) * 60) | int }}"
        turn_off:
          service: opensprinkler.stop
          data:
            entity_id: binary_sensor.poolgarden_station_running
      water_garden:
        value_template: "{{ is_state('binary_sensor.frontbeds_station_running', 'on') and is_state('binary_sensor.frontgrass_station_running', 'on') and is_state('binary_sensor.poolgarden_station_running', 'on') }}"
        turn_on:
          service: opensprinkler.run
          data:
            entity_id: switch.opensprinkler_enabled
            run_seconds:
            - 300
            - 600
            - 300
        turn_off:
          service: opensprinkler.stop
          data:
            entity_id: switch.opensprinkler_enabled
```
