### ISSUE TITLE
Expose the /curr endpoint in HASS

### ISSUE THREAD

**Issue by davidski** [vinteo/hass-opensprinkler#184]
Thank you very much for the integration! My new OS 3.0 device has current sensing capabilities, exposed at the /curr endpoint. Could this be added to the entities exposed via this integration?

**Comment by larry-glz** [comment]
i'd like to see this also.  in the mean time, i created a rest sensor to pull this value from the controller:

```
rest:
  - resource: http://IP_ADDRESS/jc?pw=MD5_HASHED_PASSWORD  # i actually used a secret entry for the URL
    sensor: 
      - name: "REST OpenSprinkler Well Valves Ctrl Current"
        value_template: "{{ value_json['curr'] }}"
```
the down side is that it doesn't update "live."  the update depends on the scan_interval
