### ISSUE TITLE
Switch for Programs

### ISSUE THREAD

**Issue by CZonin** [vinteo/hass-opensprinkler#186]
I've successfully created template switches for my zones, and I was looking to do the same for my programs. I tried formatting it the same way but it doesn't look like programs can be stopped the same way zones can.

```
      program_lawn_morning_daily:
        value_template: "{{ is_state('binary_sensor.lawn_morning_daily_program_running', 'on') }}"
        turn_on:
          service: opensprinkler.run
          data_template:
            entity_id: binary_sensor.lawn_morning_daily_program_running
        turn_off:
          service: opensprinkler.stop
          data:
            entity_id: binary_sensor.lawn_morning_daily_program_running
```

I'm thinking that I would need to replace the turn off entity with my controller_name similar to the example in the docs for stopping all zones. I don't believe I had an entity for the controller_name though. The only one that could be it would be `switch.opensprinkler_enabled` (my controller is just named 'opensprinkler'). Any ideas?
